### PR TITLE
Implemented selective initalization in FW.

### PR DESCRIPTION
**Pull request by DarkLordZach**

### CODE REVIEW

**Comment by CaptainFlareon** [comment]
Hey Zach, could you explain to me what this new Object is doing? I'm a little confused.

**Comment by DarkLordZach** [comment]
So it basically stores a list of boolean values that control whether or not certain parts of the code are enabled. 

- **Gyroscope Precise**: Angle tracking to the nearest degree. Used for gyro turns (not working) Takes about 5 seconds.
- **Gyroscope Coarse**: Records ambient gyroscope readings in y-axis (Perpendicular to surface of Earth) to prevent wheelies. 100-200 ms.
- **EOPD**: Records ambient EOPD to detect lines. 200-500 ms.
- **Color Sensor**: Records ambient color to make a better color guess. 100-200 ms.
- **Vuforia**: Initializes camera, vuforia objects and starts tracking objects. 4-5 seconds.
- **Stability**: Whether or not to use the Coarse gyroscope to prevent wheelies (on for dc, off for auto) (More parameter and less init)

So:

- **Driver Control**: All except Gyroscope Coarse and Stability is disabled. (~500 ms. from ~8 secs.)
- **Autonomous Rev 1, 2, 3**: All disabled. (~100 ms. from ~6 secs.)

(Make sure to leave your review by clicking Files changed on the top bar and the green review button. You can either approve all code or request changes. Since the master branch is protected, I cannot merge this until Jarrod, Blake, or Ben reviews.)

**Comment by DarkLordZach** [comment]
New commits incorporate new changes to master to prevent PR from going stale.

**Comment by DarkLordZach** [comment]
Commit 008ef57 also adds telemetry to track how long init takes (in ms.)

**Pull request merged**
