### PR TITLE
Fixed EMERGENCY_STOP errors in driver control and autonomous.

### PR DESCRIPTION
**Pull request by DarkLordZach**

### CODE REVIEW

**Comment by DarkLordZach** [comment]
Just took a few bites out of this file... munch munch munch

screen shot 2016-12-15 at 9 39 39 pm

om nom nom

screen shot 2016-12-15 at 9 45 59 pm

tasty!

**Comment by DarkLordZach** [comment]
So basically the culprit is this line:
screen shot 2016-12-15 at 9 55 11 pm
(actually any of the hardware.pause() lines)

If you follow that statement it goes to this method: 
screen shot 2016-12-15 at 9 56 05 pm

The `parameters.opModeIsActivated() && ` part is the fix. Basically, the loop says while the timer (reset at beginning of method) milliseconds are less than target, do absolutely nothing. The `opModeIsActivated()` part ensures that if the op mode is stopped (making that function return false instead of true), the wait stops and everything is good.

Understand? Also please test that...

Go to `Git : master` menu and click `corefw-3` and checkout and run from there.

**Comment by DarkLordZach** [comment]
Have you tested? <0_0>

**Comment by kawaiiPlatypus** [comment]
All above scenarios checked, no explosions of errors.

**Pull request merged**
